# Numerical mathematics

We will be using numpy {#sec-numpy} and scipy

## Linear algebra (`np.array` etc)

This package provides powerful and fast computations for numerical
mathematics. (Most of it is implemented in `C`.) We will only learn
about some parts of it, some linear algebra and some optimization.
Usually, it is imported via

In [1]:
import numpy as np

(Then, the functions from `numpy` are called `np.something`.) Together
with `pandas` (see **?@sec-pandas**) for data handling, this is the
basic framework for data analysis in Python3.

Let us start with linear algebra. A vector or matrix is an `np.array`.
`numpy` interprets a vector as a column vector, and

In [2]:
x = np.array([1.0, 2.0, 3.0])
A = np.array([
    [1.0, 0.0, 2.0],
    [0.0, 1.0, 1.0]
])

print("x =")
print(x)
print()
print("A =")
print(A)
print()
print("x.shape =", x.shape)
print("A.shape =", A.shape)
print("x.ndim =", x.ndim)
print("A.ndim =", A.ndim)
print("x.dtype =", x.dtype)

x =
[1. 2. 3.]

A =
[[1. 0. 2.]
 [0. 1. 1.]]

x.shape = (3,)
A.shape = (2, 3)
x.ndim = 1
A.ndim = 2
x.dtype = float64

Generally we

## Statistics (`scipy.stats`)

The `scipy`-library is a powerful which covers much of numerical
mathematics. It comes with several submodules, e.g. `scipy.linalg`
(linear algebra), `scipy.optimize` (optimization), `scipy.integrate`
(numerical integration and ODE solving), and `scipy.signal` (signal
processing). It works best with `numpy`-arrays, which we will cover in
xxx.

Here, we only describe what `scipy` has to offer in descriptive
statistics. The function names are mostly self-explanatory:

from scipy import stats

stats.norm.mean() \# mean = 0 stats.norm.pdf(0) \# density at 0
stats.norm.cdf(1.96) \# cumulative probability

data = \[1, 2, 3, 4, 5\]

stats.describe(data)

stats.ttest_1samp(data, popmean=3)

stats.ttest_ind(sample1, sample2)

stats.chisquare(\[10, 20, 30\])

stats.pearsonr(x, y)

stats.scoreatpercentile(data, 50) \# median

stats.norm.rvs(size=5)

stats.tmean(data) \# mean stats.tstd(data) \# standard deviation
stats.tvar(data) \# variance

## Random numbers (`np.rand`)

## optimization (`np.optimization`)